name: Update schema files when api changes

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
    paths:
      - 'app/**'
      - 'policy/**'
      - 'rollouts/**'

jobs:
  update-schemas-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Update Schema
        run: |
          go get -u ./...
          go mod tidy
          make gen-openapi-schema
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%s')" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated OpenAPI schema files
          tagging_message: ${{ steps.date.outputs.date }}